The data wrangling for my capstone project will be in two main parts.  

The first part will involve capturing the company data for the companies that comprise the S&P 500 Dividend Aristocrats index, as well as details for the various index benchmarks that will be used during the analysis.  These benchmarks include the main S&P 500 index, the 11 S&P 500 sector indices, and finally the exchange-traded fund (ETF) that tracks the Dividend Aristocrats index (ticker = NOBL).  

The second part will involve fetching the price, volume, dividend, and stock split data for all of the above.  

The final output will be saved .csv files for the following:
Aristocrats details
Indices and ETF details
Price, volume, dividend, and stock split data

The source for company information for the Aristocrats will be Wikipedia, and the source for price/volume/dividend/split data will be the yfinance library for python.

In [1]:
# Let's start by wrangling the companies that comprise the S&P 500 Dividend Aristocrats
import pandas as pd
import requests
from bs4 import BeautifulSoup
from io import StringIO

# Wikipedia page for S&P 500 Dividend Aristocrats
aristocrats_url = 'https://en.wikipedia.org/wiki/S%26P_500_Dividend_Aristocrats'

# Add a user-agent header to mimic a browser request
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

# Make the request with headers
response = requests.get(aristocrats_url, headers=headers)
soup = BeautifulSoup(response.content, 'html.parser')

# Create list of tables from Wikipedia page
aristocrats_companies = pd.read_html(StringIO(str(soup)))

# Verify that list of tables are returned
type(aristocrats_companies)

list

In [2]:
# Visually inspect the data scraped from Wikipedia article
print(aristocrats_companies)

[   Ticker symbol                       Company                  Sector
0            AOS                    A.O. Smith             Industrials
1            ABT           Abbott Laboratories             Health Care
2           ABBV                        AbbVie             Health Care
3            AFL                         AFLAC              Financials
4            APD      Air Products & Chemicals               Materials
..           ...                           ...                     ...
64          TROW        T Rowe Price Group Inc              Financials
65           TGT                   Target Corp  Consumer Discretionary
66           GWW                W. W. Grainger             Industrials
67           WMT                  Walmart Inc.        Consumer Staples
68           WST  West Pharmaceutical Services             Health Care

[69 rows x 3 columns],     Year                                              Added  \
0   2025  Erie Indemnity (ERIE), Eversource Energy (ES),...
1   2024                                Fastenal Co. (FAST)
2   2023  CH Robinson Worldwide (CHRW), Nordson (NDSN), ...
3   2022  Brown & Brown, Inc. (BRO) and Church & Dwight ...
4   2021  IBM (IBM), NextEra Energy (NEE) and West Pharm...
5   2020  Amcor (AMCR), Atmos Energy (ATO), Realty Incom...
6   2019  Chubb Limited (CB), People's United Financial ...
7   2018                                               none
8   2017                                               none
9   2016                                               none
10  2015                                               none
11  2014                                               none
12  2013                                               none
13  2012  AT&T (T), Colgate-Palmolive (CL), Franklin Tem...
14  2011  Ecolab (ECL), Hormel Foods (HRL), and McCormic...
15  2010                                Brown Forman (BF.B)
16  2009     Bemis Company (BMS) and Leggett & Platt (LEG).

                                              Removed  Reference(s)
0                                                none           [7]
1   Walgreens Boots Alliance Inc. (WBA) and the 3M...        [8][9]
2                                VF Corporation (VFC)  [10][11][12]
3   AT&T Inc. (T); People's United Financial, Inc....  [13][14][15]
4   Raytheon (RTX), Carrier Global (CARR), Otis Wo...          [16]
5      Ross Stores (ROST) and Helmerich & Payne (HP).          [17]
6                                                none          [18]
7                                                none           NaN
8                                                none           NaN
9   Chubb Corp (CB) (upon acquisition by ACE Limit...           NaN
10  Family Dollar Stores (FDO) (after purchase by ...           NaN
11  Bemis (BMS) (after removal from the S&P 500 in...           NaN
12                                 Pitney Bowes (PBI)           NaN
13                                  CenturyLink (CTL)           NaN
14                                               none           NaN
15  Avery Dennison (AVY), BB&T (BBT), Gannett (GCI...           NaN
16  Anheuser Busch (BUD) (acquired by InBev), Bank...           NaN  ]

In [3]:
# Fetch 1st table from list.
# This table lists the current companies in the index.
# Verify DataFrame from 1st table's contents and visually inspect first few records.
aristocrats = aristocrats_companies[0]
print(type(aristocrats))
print(aristocrats.head(20))

<class 'pandas.core.frame.DataFrame'>
   Ticker symbol                    Company                  Sector
0            AOS                 A.O. Smith             Industrials
1            ABT        Abbott Laboratories             Health Care
2           ABBV                     AbbVie             Health Care
3            AFL                      AFLAC              Financials
4            APD   Air Products & Chemicals               Materials
5            ALB      Albemarle Corporation               Materials
6           AMCR                      Amcor               Materials
7            ADM  Archer-Daniels-Midland Co        Consumer Staples
8            ATO          Atmos Energy Corp               Utilities
9            ADP  Automatic Data Processing  Information Technology
10           BDX      Becton Dickinson & Co             Health Care
11           BRO         Brown & Brown Inc.              Financials
12          BF.B     Brown–Forman (class B)        Consumer Staples
13           CAH        Cardinal Health Inc             Health Care
14           CAT            Caterpillar Inc             Industrials
15          CHRW              C.H. Robinson             Industrials
16           CVX               Chevron Corp                  Energy
17            CB              Chubb Limited              Financials
18           CHD            Church & Dwight        Consumer Staples
19          CINF  Cincinnati Financial Corp              Financials

In [4]:
# Change Ticker symbol column header to just Ticker
aristocrats.rename(columns={"Ticker symbol": "Ticker"}, inplace=True)
aristocrats.head()

  Ticker                   Company       Sector
0    AOS                A.O. Smith  Industrials
1    ABT       Abbott Laboratories  Health Care
2   ABBV                    AbbVie  Health Care
3    AFL                     AFLAC   Financials
4    APD  Air Products & Chemicals    Materials

In [5]:
# Fetch 2nd table from list.
# This table is focused on additions and removals of companies over the life of the index.
# Company survivorship of an index is an integral part of the backtesting of any investment strategy.
additions_removals = aristocrats_companies[1]
print(type(additions_removals))
print(additions_removals)

<class 'pandas.core.frame.DataFrame'>
    Year                                              Added  \
0   2025  Erie Indemnity (ERIE), Eversource Energy (ES),...
1   2024                                Fastenal Co. (FAST)
2   2023  CH Robinson Worldwide (CHRW), Nordson (NDSN), ...
3   2022  Brown & Brown, Inc. (BRO) and Church & Dwight ...
4   2021  IBM (IBM), NextEra Energy (NEE) and West Pharm...
5   2020  Amcor (AMCR), Atmos Energy (ATO), Realty Incom...
6   2019  Chubb Limited (CB), People's United Financial ...
7   2018                                               none
8   2017                                               none
9   2016                                               none
10  2015                                               none
11  2014                                               none
12  2013                                               none
13  2012  AT&T (T), Colgate-Palmolive (CL), Franklin Tem...
14  2011  Ecolab (ECL), Hormel Foods (HRL), and McCormic...
15  2010                                Brown Forman (BF.B)
16  2009     Bemis Company (BMS) and Leggett & Platt (LEG).

                                              Removed  Reference(s)
0                                                none           [7]
1   Walgreens Boots Alliance Inc. (WBA) and the 3M...        [8][9]
2                                VF Corporation (VFC)  [10][11][12]
3   AT&T Inc. (T); People's United Financial, Inc....  [13][14][15]
4   Raytheon (RTX), Carrier Global (CARR), Otis Wo...          [16]
5      Ross Stores (ROST) and Helmerich & Payne (HP).          [17]
6                                                none          [18]
7                                                none           NaN
8                                                none           NaN
9   Chubb Corp (CB) (upon acquisition by ACE Limit...           NaN
10  Family Dollar Stores (FDO) (after purchase by ...           NaN
11  Bemis (BMS) (after removal from the S&P 500 in...           NaN
12                                 Pitney Bowes (PBI)           NaN
13                                  CenturyLink (CTL)           NaN
14                                               none           NaN
15  Avery Dennison (AVY), BB&T (BBT), Gannett (GCI...           NaN
16  Anheuser Busch (BUD) (acquired by InBev), Bank...           NaN

In [6]:
# I intend to start the machine learning with year 2013 as NOBL was launched in 2013;
# therefore, I only require the additions and removals since 2013 (inclusive).
additions_removals = additions_removals[additions_removals['Year'] >= 2013]
additions_removals

,Year,Added,Removed,Reference(s)
0,2025,"Erie Indemnity (ERIE), Eversource Energy (ES),...",none,[7]
1,2024,Fastenal Co. (FAST),Walgreens Boots Alliance Inc. (WBA) and the 3M...,[8][9]
2,2023,"CH Robinson Worldwide (CHRW), Nordson (NDSN), ...",VF Corporation (VFC),[10][11][12]
3,2022,"Brown & Brown, Inc. (BRO) and Church & Dwight ...","AT&T Inc. (T); People's United Financial, Inc....",[13][14][15]
4,2021,"IBM (IBM), NextEra Energy (NEE) and West Pharm...","Raytheon (RTX), Carrier Global (CARR), Otis Wo...",[16]
5,2020,"Amcor (AMCR), Atmos Energy (ATO), Realty Incom...",Ross Stores (ROST) and Helmerich & Payne (HP).,[17]
6,2019,"Chubb Limited (CB), People's United Financial ...",none,[18]
7,2018,none,none,NaN
8,2017,none,none,NaN
9,2016,none,Chubb Corp (CB) (upon acquisition by ACE Limit...,NaN
10,2015,none,Family Dollar Stores (FDO) (after purchase by ...,NaN
11,2014,none,Bemis (BMS) (after removal from the S&P 500 in...,NaN
12,2013,none,Pitney Bowes (PBI),NaN

In [7]:
# Parse the tickers from the 'Added' column and include in new 'Added_Tickers' column
additions_removals = additions_removals.copy()
additions_removals['Added_Tickers'] = additions_removals.loc[:, 'Added'].str.findall(r'\(([A-Z\s]+)\)')

# Parse the tickers from the 'Removed' column and include in new 'Removed_Tickers' column
additions_removals = additions_removals.copy()
additions_removals['Removed_Tickers'] = additions_removals.loc[:, 'Removed'].str.findall(r'\(([A-Z\s]+)\)')
additions_removals

,Year,Added,Removed,Reference(s),Added_Tickers,Removed_Tickers
0,2025,"Erie Indemnity (ERIE), Eversource Energy (ES),...",none,[7],"[ERIE, ES, RGLD, FDS]",[]
1,2024,Fastenal Co. (FAST),Walgreens Boots Alliance Inc. (WBA) and the 3M...,[8][9],[FAST],"[WBA, MMM]"
2,2023,"CH Robinson Worldwide (CHRW), Nordson (NDSN), ...",VF Corporation (VFC),[10][11][12],"[CHRW, NDSN, SJM, KVUE]",[VFC]
3,2022,"Brown & Brown, Inc. (BRO) and Church & Dwight ...","AT&T Inc. (T); People's United Financial, Inc....",[13][14][15],"[BRO, CHD]","[T, PBCT]"
4,2021,"IBM (IBM), NextEra Energy (NEE) and West Pharm...","Raytheon (RTX), Carrier Global (CARR), Otis Wo...",[16],"[IBM, NEE, WST]","[RTX, CARR, OTIS, SYK, LEG]"
5,2020,"Amcor (AMCR), Atmos Energy (ATO), Realty Incom...",Ross Stores (ROST) and Helmerich & Payne (HP).,[17],"[AMCR, ATO, O, ESS, ROST, ALB, EXPD, CARR, OTIS]","[ROST, HP]"
6,2019,"Chubb Limited (CB), People's United Financial ...",none,[18],"[CB, PBCT, CAT, UTX]",[]
7,2018,none,none,NaN,[],[]
8,2017,none,none,NaN,[],[]
9,2016,none,Chubb Corp (CB) (upon acquisition by ACE Limit...,NaN,[],"[CB, ACE]"
10,2015,none,Family Dollar Stores (FDO) (after purchase by ...,NaN,[],"[FDO, SIAL]"
11,2014,none,Bemis (BMS) (after removal from the S&P 500 in...,NaN,[],[BMS]
12,2013,none,Pitney Bowes (PBI),NaN,[],[PBI]

In [8]:
# The Added, Removed, and Reference(s) columns are no longer required at this point
additions_removals = additions_removals.drop(columns=['Added', 'Removed', 'Reference(s)'])
additions_removals

,Year,Added_Tickers,Removed_Tickers
0,2025,"[ERIE, ES, RGLD, FDS]",[]
1,2024,[FAST],"[WBA, MMM]"
2,2023,"[CHRW, NDSN, SJM, KVUE]",[VFC]
3,2022,"[BRO, CHD]","[T, PBCT]"
4,2021,"[IBM, NEE, WST]","[RTX, CARR, OTIS, SYK, LEG]"
5,2020,"[AMCR, ATO, O, ESS, ROST, ALB, EXPD, CARR, OTIS]","[ROST, HP]"
6,2019,"[CB, PBCT, CAT, UTX]",[]
7,2018,[],[]
8,2017,[],[]
9,2016,[],"[CB, ACE]"
10,2015,[],"[FDO, SIAL]"
11,2014,[],[BMS]
12,2013,[],[PBI]

In [9]:
# Explode the list of tickers in the Added_Tickers column
# Insert the content into new DataFrame along with Year value
additions_filtered = (additions_removals[additions_removals['Added_Tickers'].apply(
    lambda x: isinstance(x, list) and len(x) > 0)]
    .explode('Added_Tickers')
    .rename(columns={'Added_Tickers': 'Ticker', 'Year': 'Year_Added'})
    [['Year_Added', 'Ticker']]
    .reset_index(drop=True))


# Explode the list of tickers in the Removed_Tickers column
# Insert the content into new DataFrame along with Year value
removals_filtered = (additions_removals[additions_removals['Removed_Tickers'].apply(
    lambda x: isinstance(x, list) and len(x) > 0)]
    .explode('Removed_Tickers')
    .rename(columns={'Removed_Tickers': 'Ticker', 'Year': 'Year_Removed'})
    [['Year_Removed', 'Ticker']]
    .reset_index(drop=True))

# Merge the two above DataFrames into a single source of truth
combined_filtered = pd.merge(additions_filtered, 
                            removals_filtered, 
                            on='Ticker', 
                            how='outer')

# Reorder the columns
col_reorder = ['Ticker', 'Year_Added', 'Year_Removed']
combined_filtered = combined_filtered[col_reorder]

# Examine the final result
combined_filtered

   Ticker  Year_Added  Year_Removed
0     ACE         NaN        2016.0
1     ALB      2020.0           NaN
2    AMCR      2020.0           NaN
3     ATO      2020.0           NaN
4     BMS         NaN        2014.0
5     BRO      2022.0           NaN
6    CARR      2020.0        2021.0
7     CAT      2019.0           NaN
8      CB      2019.0        2016.0
9     CHD      2022.0           NaN
10   CHRW      2023.0           NaN
11   ERIE      2025.0           NaN
12     ES      2025.0           NaN
13    ESS      2020.0           NaN
14   EXPD      2020.0           NaN
15   FAST      2024.0           NaN
16    FDO         NaN        2015.0
17    FDS      2025.0           NaN
18     HP         NaN        2020.0
19    IBM      2021.0           NaN
20   KVUE      2023.0           NaN
21    LEG         NaN        2021.0
22    MMM         NaN        2024.0
23   NDSN      2023.0           NaN
24    NEE      2021.0           NaN
25      O      2020.0           NaN
26   OTIS      2020.0        2021.0
27   PBCT      2019.0        2022.0
28    PBI         NaN        2013.0
29   RGLD      2025.0           NaN
30   ROST      2020.0        2020.0
31    RTX         NaN        2021.0
32   SIAL         NaN        2015.0
33    SJM      2023.0           NaN
34    SYK         NaN        2021.0
35      T         NaN        2022.0
36    UTX      2019.0           NaN
37    VFC         NaN        2023.0
38    WBA         NaN        2024.0
39    WST      2021.0           NaN

In [10]:
# Since I am having all additions and removals occur on January 1st,
# any ticker that is added and removed in same year should be omitted.
combined_filtered = combined_filtered[combined_filtered['Year_Added'] != combined_filtered['Year_Removed']]
combined_filtered.reset_index(drop=True, inplace=True) 
combined_filtered

   Ticker  Year_Added  Year_Removed
0     ACE         NaN        2016.0
1     ALB      2020.0           NaN
2    AMCR      2020.0           NaN
3     ATO      2020.0           NaN
4     BMS         NaN        2014.0
5     BRO      2022.0           NaN
6    CARR      2020.0        2021.0
7     CAT      2019.0           NaN
8      CB      2019.0        2016.0
9     CHD      2022.0           NaN
10   CHRW      2023.0           NaN
11   ERIE      2025.0           NaN
12     ES      2025.0           NaN
13    ESS      2020.0           NaN
14   EXPD      2020.0           NaN
15   FAST      2024.0           NaN
16    FDO         NaN        2015.0
17    FDS      2025.0           NaN
18     HP         NaN        2020.0
19    IBM      2021.0           NaN
20   KVUE      2023.0           NaN
21    LEG         NaN        2021.0
22    MMM         NaN        2024.0
23   NDSN      2023.0           NaN
24    NEE      2021.0           NaN
25      O      2020.0           NaN
26   OTIS      2020.0        2021.0
27   PBCT      2019.0        2022.0
28    PBI         NaN        2013.0
29   RGLD      2025.0           NaN
30    RTX         NaN        2021.0
31   SIAL         NaN        2015.0
32    SJM      2023.0           NaN
33    SYK         NaN        2021.0
34      T         NaN        2022.0
35    UTX      2019.0           NaN
36    VFC         NaN        2023.0
37    WBA         NaN        2024.0
38    WST      2021.0           NaN

In [11]:
# Merge the aristocrats and combined_filters DataFrames
aristocrats_complete = pd.merge(aristocrats, 
                            combined_filtered, 
                            on='Ticker', 
                            how='outer')
aristocrats_complete.head(20)

,Ticker,Company,Sector,Year_Added,Year_Removed
0,ABBV,AbbVie,Health Care,NaN,NaN
1,ABT,Abbott Laboratories,Health Care,NaN,NaN
2,ACE,NaN,NaN,NaN,2016.0
3,ADM,Archer-Daniels-Midland Co,Consumer Staples,NaN,NaN
4,ADP,Automatic Data Processing,Information Technology,NaN,NaN
5,AFL,AFLAC,Financials,NaN,NaN
6,ALB,Albemarle Corporation,Materials,2020.0,NaN
7,AMCR,Amcor,Materials,2020.0,NaN
8,AOS,A.O. Smith,Industrials,NaN,NaN
9,APD,Air Products & Chemicals,Materials,NaN,NaN
10,ATO,Atmos Energy Corp,Utilities,2020.0,NaN
11,BDX,Becton Dickinson & Co,Health Care,NaN,NaN
12,BEN,Franklin Resources Inc,Financials,NaN,NaN
13,BF.B,Brown–Forman (class B),Consumer Staples,NaN,NaN
14,BMS,NaN,NaN,NaN,2014.0
15,BRO,Brown & Brown Inc.,Financials,2022.0,NaN
16,CAH,Cardinal Health Inc,Health Care,NaN,NaN
17,CARR,NaN,NaN,2020.0,2021.0
18,CAT,Caterpillar Inc,Industrials,2019.0,NaN
19,CB,Chubb Limited,Financials,2019.0,2016.0

In [12]:
# For those records where Year_Added is NaN, insert 2013 (start date for
# time series machine learning)
aristocrats_complete['Year_Added'] = aristocrats_complete['Year_Added'].fillna(2013)

# For those records where Year_Removed is NaN, insert 2030 (arbitrary year
# in near future)
aristocrats_complete['Year_Removed'] = aristocrats_complete['Year_Removed'].fillna(2030)

aristocrats_complete.head(20)

,Ticker,Company,Sector,Year_Added,Year_Removed
0,ABBV,AbbVie,Health Care,2013.0,2030.0
1,ABT,Abbott Laboratories,Health Care,2013.0,2030.0
2,ACE,NaN,NaN,2013.0,2016.0
3,ADM,Archer-Daniels-Midland Co,Consumer Staples,2013.0,2030.0
4,ADP,Automatic Data Processing,Information Technology,2013.0,2030.0
5,AFL,AFLAC,Financials,2013.0,2030.0
6,ALB,Albemarle Corporation,Materials,2020.0,2030.0
7,AMCR,Amcor,Materials,2020.0,2030.0
8,AOS,A.O. Smith,Industrials,2013.0,2030.0
9,APD,Air Products & Chemicals,Materials,2013.0,2030.0
10,ATO,Atmos Energy Corp,Utilities,2020.0,2030.0
11,BDX,Becton Dickinson & Co,Health Care,2013.0,2030.0
12,BEN,Franklin Resources Inc,Financials,2013.0,2030.0
13,BF.B,Brown–Forman (class B),Consumer Staples,2013.0,2030.0
14,BMS,NaN,NaN,2013.0,2014.0
15,BRO,Brown & Brown Inc.,Financials,2022.0,2030.0
16,CAH,Cardinal Health Inc,Health Care,2013.0,2030.0
17,CARR,NaN,NaN,2020.0,2021.0
18,CAT,Caterpillar Inc,Industrials,2019.0,2030.0
19,CB,Chubb Limited,Financials,2019.0,2016.0

**Note:**  Yfinance does not currently accept the period (.) delimiter to distinguish share class for the ticker symbol, and any call to yfinance using a ticker that has this delimiter (e.g., "BF.B") will fail.  Yfinance utilizes the hyphen char (-) instead.

In [13]:
# Identify any tickers that have period (.) char as substring and  
# replace with hyphen (-) char.
aristocrats_complete['Ticker'] = aristocrats_complete['Ticker'].str.\
                                    replace('.', '-', regex=False)
aristocrats_complete.head(20)

,Ticker,Company,Sector,Year_Added,Year_Removed
0,ABBV,AbbVie,Health Care,2013.0,2030.0
1,ABT,Abbott Laboratories,Health Care,2013.0,2030.0
2,ACE,NaN,NaN,2013.0,2016.0
3,ADM,Archer-Daniels-Midland Co,Consumer Staples,2013.0,2030.0
4,ADP,Automatic Data Processing,Information Technology,2013.0,2030.0
5,AFL,AFLAC,Financials,2013.0,2030.0
6,ALB,Albemarle Corporation,Materials,2020.0,2030.0
7,AMCR,Amcor,Materials,2020.0,2030.0
8,AOS,A.O. Smith,Industrials,2013.0,2030.0
9,APD,Air Products & Chemicals,Materials,2013.0,2030.0
10,ATO,Atmos Energy Corp,Utilities,2020.0,2030.0
11,BDX,Becton Dickinson & Co,Health Care,2013.0,2030.0
12,BEN,Franklin Resources Inc,Financials,2013.0,2030.0
13,BF-B,Brown–Forman (class B),Consumer Staples,2013.0,2030.0
14,BMS,NaN,NaN,2013.0,2014.0
15,BRO,Brown & Brown Inc.,Financials,2022.0,2030.0
16,CAH,Cardinal Health Inc,Health Care,2013.0,2030.0
17,CARR,NaN,NaN,2020.0,2021.0
18,CAT,Caterpillar Inc,Industrials,2019.0,2030.0
19,CB,Chubb Limited,Financials,2019.0,2016.0

In [14]:
# There are several tickers in the DataFrame with missing Company and Sector. 
# Use yfinance to fetch these values.  I suspect that some of these tickers
# will return Company=None and Sector=None as they have since been delisted
# from the exchanges.
import yfinance as yf
import time

for index, row in aristocrats_complete.iterrows():
    if not pd.isna(row['Company']):
        continue
    try:
        info = yf.Ticker(row['Ticker']).info
        aristocrats_complete.at[index, 'Sector'] = info.get('sector')
        aristocrats_complete.at[index, 'Company'] = info.get('longName')
        time.sleep(0.5)
    except Exception as e:
        print(f"Error fetching {row['Ticker']}: {e}")

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: WBA"}}}

**Note:** The 404 error returned for WBA indicates that WBA is the first of a possible handful of symbols that have been delisted from the exchanges.  I'll need to check further on this.

In [15]:
# Quick look at the results
print(aristocrats_complete.head(15))
print(aristocrats_complete.tail(15))

   Ticker                    Company                  Sector  Year_Added  \
0    ABBV                     AbbVie             Health Care      2013.0
1     ABT        Abbott Laboratories             Health Care      2013.0
2     ACE                       None                    None      2013.0
3     ADM  Archer-Daniels-Midland Co        Consumer Staples      2013.0
4     ADP  Automatic Data Processing  Information Technology      2013.0
5     AFL                      AFLAC              Financials      2013.0
6     ALB      Albemarle Corporation               Materials      2020.0
7    AMCR                      Amcor               Materials      2020.0
8     AOS                 A.O. Smith             Industrials      2013.0
9     APD   Air Products & Chemicals               Materials      2013.0
10    ATO          Atmos Energy Corp               Utilities      2020.0
11    BDX      Becton Dickinson & Co             Health Care      2013.0
12    BEN     Franklin Resources Inc              Financials      2013.0
13   BF-B     Brown–Forman (class B)        Consumer Staples      2013.0
14    BMS        Bemis Company, Inc.                    None      2013.0

    Year_Removed
0         2030.0
1         2030.0
2         2016.0
3         2030.0
4         2030.0
5         2030.0
6         2030.0
7         2030.0
8         2030.0
9         2030.0
10        2030.0
11        2030.0
12        2030.0
13        2030.0
14        2014.0
   Ticker                       Company                  Sector  Year_Added  \
72   SIAL                          None                    None      2013.0
73    SJM     The J. M. Smucker Company        Consumer Staples      2023.0
74   SPGI                S&P Global Inc              Financials      2013.0
75    SWK        Stanley Black & Decker             Industrials      2013.0
76    SYK           Stryker Corporation              Healthcare      2013.0
77    SYY                    Sysco Corp        Consumer Staples      2013.0
78      T                     AT&T Inc.  Communication Services      2013.0
79    TGT                   Target Corp  Consumer Discretionary      2013.0
80   TROW        T Rowe Price Group Inc              Financials      2013.0
81    UTX                          None                    None      2019.0
82    VFC              V.F. Corporation       Consumer Cyclical      2013.0
83    WBA                          None                    None      2013.0
84    WMT                  Walmart Inc.        Consumer Staples      2013.0
85    WST  West Pharmaceutical Services             Health Care      2021.0
86    XOM              Exxon Mobil Corp                  Energy      2013.0

    Year_Removed
72        2015.0
73        2030.0
74        2030.0
75        2030.0
76        2021.0
77        2030.0
78        2022.0
79        2030.0
80        2030.0
81        2030.0
82        2023.0
83        2024.0
84        2030.0
85        2030.0
86        2030.0

In [16]:
# Return those tickers that I suspect as being delisted.
# I suspect Sector=None will be returned for all.
delisted = aristocrats_complete[aristocrats_complete['Company'].isna()]
delisted

   Ticker Company Sector  Year_Added  Year_Removed
2     ACE    None   None      2013.0        2016.0
36    FDO    None   None      2013.0        2015.0
62   PBCT    None   None      2019.0        2022.0
72   SIAL    None   None      2013.0        2015.0
81    UTX    None   None      2019.0        2030.0
83    WBA    None   None      2013.0        2024.0

In [17]:
# Need to confirm my suspicions by attempting to fetch price data for these
for symbol in delisted['Ticker']:
    price_hist = yf.Ticker(symbol).history(period='max', auto_adjust=False)
    len(price_hist)

$ACE: possibly delisted; no price data found  (1d 1927-07-13 -> 2026-06-18)
$FDO: possibly delisted; no price data found  (1d 1927-07-13 -> 2026-06-18)
$PBCT: possibly delisted; no timezone found
$SIAL: possibly delisted; no price data found  (1d 1927-07-13 -> 2026-06-18)
$UTX: possibly delisted; no timezone found
$WBA: possibly delisted; no timezone found

In [18]:
# Remove the delisted stocks as yfinance does not have price data for these
aristocrats_complete.drop(delisted.index, inplace=True)
aristocrats_complete.reset_index(drop=True, inplace=True) 
aristocrats_complete.tail(15)

,Ticker,Company,Sector,Year_Added,Year_Removed
66,ROP,Roper Technologies,Industrials,2013.0,2030.0
67,RTX,RTX Corporation,Industrials,2013.0,2021.0
68,SHW,Sherwin-Williams,Materials,2013.0,2030.0
69,SJM,The J. M. Smucker Company,Consumer Staples,2023.0,2030.0
70,SPGI,S&P Global Inc,Financials,2013.0,2030.0
71,SWK,Stanley Black & Decker,Industrials,2013.0,2030.0
72,SYK,Stryker Corporation,Healthcare,2013.0,2021.0
73,SYY,Sysco Corp,Consumer Staples,2013.0,2030.0
74,T,AT&T Inc.,Communication Services,2013.0,2022.0
75,TGT,Target Corp,Consumer Discretionary,2013.0,2030.0
76,TROW,T Rowe Price Group Inc,Financials,2013.0,2030.0
77,VFC,V.F. Corporation,Consumer Cyclical,2013.0,2023.0
78,WMT,Walmart Inc.,Consumer Staples,2013.0,2030.0
79,WST,West Pharmaceutical Services,Health Care,2021.0,2030.0
80,XOM,Exxon Mobil Corp,Energy,2013.0,2030.0

In [19]:
# Determine any records where Sector value is missing
aristocrats_complete[aristocrats_complete['Sector'].isna()]

   Ticker              Company Sector  Year_Added  Year_Removed
13    BMS  Bemis Company, Inc.   None      2013.0        2014.0

In [20]:
# Some research on Google showed that Bemis Company Inc. was the Materials 
# sector of the economy
aristocrats_complete.loc[aristocrats_complete['Ticker'] == 'BMS', 'Sector'] = 'Materials'

In [21]:
# The above visual inspection shows that some of the Sector values appear to be 
# different depending from where they were fetched (Wikipedia versus yfinance).  
# Need to double check this.
aristocrats_complete['Sector'].unique()

array(['Health Care', 'Consumer Staples', 'Information Technology',
       'Financials', 'Materials', 'Industrials', 'Utilities', 'Energy',
       'Real Estate', 'Consumer Discretionary', 'Consumer Cyclical',
       'Basic Materials', 'Healthcare', 'Communication Services'],
      dtype=object)

In [22]:
# For those Sector verbiages showing discrepancies, realign using intended verbiages. 
# These same verbiages will be used when creating the dictionary of indices further
# down in this Notebook.
aristocrats_complete['Sector'] = aristocrats_complete['Sector'].replace('Healthcare', 'Health Care')
aristocrats_complete['Sector'] = aristocrats_complete['Sector'].replace('Basic Materials', 'Materials')
aristocrats_complete['Sector'] = aristocrats_complete['Sector'].replace('Consumer Cyclical', 'Consumer Discretionary')
aristocrats_complete['Sector'].unique()

# Quick visual inspection
aristocrats_complete.head(15)
aristocrats_complete.tail(15)

,Ticker,Company,Sector,Year_Added,Year_Removed
66,ROP,Roper Technologies,Industrials,2013.0,2030.0
67,RTX,RTX Corporation,Industrials,2013.0,2021.0
68,SHW,Sherwin-Williams,Materials,2013.0,2030.0
69,SJM,The J. M. Smucker Company,Consumer Staples,2023.0,2030.0
70,SPGI,S&P Global Inc,Financials,2013.0,2030.0
71,SWK,Stanley Black & Decker,Industrials,2013.0,2030.0
72,SYK,Stryker Corporation,Health Care,2013.0,2021.0
73,SYY,Sysco Corp,Consumer Staples,2013.0,2030.0
74,T,AT&T Inc.,Communication Services,2013.0,2022.0
75,TGT,Target Corp,Consumer Discretionary,2013.0,2030.0
76,TROW,T Rowe Price Group Inc,Financials,2013.0,2030.0
77,VFC,V.F. Corporation,Consumer Discretionary,2013.0,2023.0
78,WMT,Walmart Inc.,Consumer Staples,2013.0,2030.0
79,WST,West Pharmaceutical Services,Health Care,2021.0,2030.0
80,XOM,Exxon Mobil Corp,Energy,2013.0,2030.0

In [24]:
# Iterate through the aristocrats_complete DataFrame and fetch
# historical price and dividend data since 1/1/2013.
stock_symbols = aristocrats_complete['Ticker']
stock_data = {
    symbol: yf.Ticker(symbol).history(start='2013-01-01', auto_adjust=False) for symbol in stock_symbols
}
print("Done")

# Quick look at dictionary of market data
print(stock_data)

Done
{'ABBV':                                  Open        High         Low       Close  \
Date
2013-01-02 00:00:00-05:00   34.919998   35.400002   34.099998   35.119999
2013-01-03 00:00:00-05:00   35.000000   35.000000   34.160000   34.830002
2013-01-04 00:00:00-05:00   34.619999   34.889999   34.250000   34.389999
2013-01-07 00:00:00-05:00   34.150002   35.450001   34.150002   34.459999
2013-01-08 00:00:00-05:00   34.290001   34.639999   33.360001   33.709999
...                               ...         ...         ...         ...
2026-06-12 00:00:00-04:00  227.500000  228.399994  224.320007  227.729996
2026-06-15 00:00:00-04:00  226.000000  226.500000  220.000000  221.589996
2026-06-16 00:00:00-04:00  223.309998  223.500000  219.149994  222.470001
2026-06-17 00:00:00-04:00  222.399994  222.839996  218.830002  221.229996
2026-06-18 00:00:00-04:00  221.369995  222.300003  215.369995  216.399994

                            Adj Close    Volume  Dividends  Stock Splits
Date
2013-01-02 00:00:00-05:00   20.561075  13767900        0.0           0.0
2013-01-03 00:00:00-05:00   20.391291  16739300        0.0           0.0
2013-01-04 00:00:00-05:00   20.133686  21372100        0.0           0.0
2013-01-07 00:00:00-05:00   20.174667  17897100        0.0           0.0
2013-01-08 00:00:00-05:00   19.735580  17863300        0.0           0.0
...                               ...       ...        ...           ...
2026-06-12 00:00:00-04:00  227.729996   4086500        0.0           0.0
2026-06-15 00:00:00-04:00  221.589996   5261900        0.0           0.0
2026-06-16 00:00:00-04:00  222.470001   5945500        0.0           0.0
2026-06-17 00:00:00-04:00  221.229996   5624200        0.0           0.0
2026-06-18 00:00:00-04:00  216.399994   3183222        0.0           0.0

[3386 rows x 8 columns], 'ABT':                                 Open       High        Low      Close  \
Date
2013-01-02 00:00:00-05:00  32.299999  32.450001  31.639999  32.049999
2013-01-03 00:00:00-05:00  32.900002  33.380001  32.740002  33.270000
2013-01-04 00:00:00-05:00  33.330002  33.430000  32.849998  33.070000
2013-01-07 00:00:00-05:00  33.020000  33.340000  32.849998  33.340000
2013-01-08 00:00:00-05:00  33.290001  33.560001  33.080002  33.349998
...                              ...        ...        ...        ...
2026-06-12 00:00:00-04:00  89.620003  90.290001  87.070000  88.180000
2026-06-15 00:00:00-04:00  88.260002  89.160004  87.730003  88.669998
2026-06-16 00:00:00-04:00  89.360001  90.690002  88.830002  90.620003
2026-06-17 00:00:00-04:00  90.360001  91.580002  87.870003  88.500000
2026-06-18 00:00:00-04:00  88.639999  89.440002  88.389999  88.900002

                           Adj Close    Volume  Dividends  Stock Splits
Date
2013-01-02 00:00:00-05:00  24.736917  20266400        0.0      2.084202
2013-01-03 00:00:00-05:00  25.678528  22148200        0.0      0.000000
2013-01-04 00:00:00-05:00  25.524174  15820100        0.0      0.000000
2013-01-07 00:00:00-05:00  25.732563  13120000        0.0      0.000000
2013-01-08 00:00:00-05:00  25.740286  15042300        0.0      0.000000
...                              ...       ...        ...           ...
2026-06-12 00:00:00-04:00  88.180000  13758700        0.0      0.000000
2026-06-15 00:00:00-04:00  88.669998  10950100        0.0      0.000000
2026-06-16 00:00:00-04:00  90.620003  12740700        0.0      0.000000
2026-06-17 00:00:00-04:00  88.500000  13052200        0.0      0.000000
2026-06-18 00:00:00-04:00  88.900002   4699397        0.0      0.000000

[3386 rows x 8 columns], 'ADM':                                 Open       High        Low      Close  \
Date
2013-01-02 00:00:00-05:00  28.139999  28.680000  28.049999  28.670000
2013-01-03 00:00:00-05:00  28.760000  28.760000  28.299999  28.440001
2013-01-04 00:00:00-05:00  28.500000  29.290001  28.459999  29.219999
2013-01-07 00:00:00-05:00  29.100000  29.100000  27.930000  28.010000
2013-01-08 00:00:00-05:00  27.930000  28.360001  27.900000  28.340000
...                              ...        ...        ...        ...
2026-06-12 00:00:00-04:00  79.169998  80.250000  78.180000  80.239998
2026-06-15 00:00:00-04:00  79.059998  79.419998  77.720001  79.269997
2026-06-16 00:00:00-04:00  79.050003  79.250000  77.519997  78.019997
2026-06-17 00:00:00-04:00  77.500000  77.500000  75.599998  76.500000
2026-06-18 00:00:00-04:00  76.660004  76.660004  74.279999  74.550102

                           Adj Close   Volume  Dividends  Stock Splits
Date
2013-01-02 00:00:00-05:00  19.620430  6677100        0.0           0.0
2013-01-03 00:00:00-05:00  19.463037  3970700        0.0           0.0
2013-01-04 00:00:00-05:00  19.996822  5842400        0.0           0.0
2013-01-07 00:00:00-05:00  19.168756  8339200        0.0           0.0
2013-01-08 00:00:00-05:00  19.394598  3880400        0.0           0.0
...                              ...      ...        ...           ...
2026-06-12 00:00:00-04:00  80.239998  2033500        0.0           0.0
2026-06-15 00:00:00-04:00  79.269997  3456600        0.0           0.0
2026-06-16 00:00:00-04:00  78.019997  2875500        0.0           0.0
2026-06-17 00:00:00-04:00  76.500000  3448900        0.0           0.0
2026-06-18 00:00:00-04:00  74.550102  1582148        0.0           0.0

[3386 rows x 8 columns], 'ADP':                                  Open        High         Low       Close  \
Date
2013-01-02 00:00:00-05:00   50.974541   51.404739   50.702370   51.264267
2013-01-03 00:00:00-05:00   51.457420   51.650570   50.702370   51.466198
2013-01-04 00:00:00-05:00   51.641792   52.054436   51.413521   51.922737
2013-01-07 00:00:00-05:00   51.641792   51.878841   51.299385   51.720806
2013-01-08 00:00:00-05:00   51.615452   52.080772   51.448639   52.019314
...                               ...         ...         ...         ...
2026-06-12 00:00:00-04:00  224.179993  227.199997  221.839996  226.210007
2026-06-15 00:00:00-04:00  224.360001  226.539993  222.330002  223.220001
2026-06-16 00:00:00-04:00  224.690002  225.789993  220.220001  222.000000
2026-06-17 00:00:00-04:00  220.160004  224.039993  216.789993  218.759995
2026-06-18 00:00:00-04:00  218.559998  218.740005  215.297394  217.845001

                            Adj Close   Volume  Dividends  Stock Splits
Date
2013-01-02 00:00:00-05:00   37.814606  3217561        0.0           0.0
2013-01-03 00:00:00-05:00   37.963558  2564459        0.0           0.0
2013-01-04 00:00:00-05:00   38.300316  2113301        0.0           0.0
2013-01-07 00:00:00-05:00   38.151367  1712828        0.0           0.0
2013-01-08 00:00:00-05:00   38.371559  1924341        0.0           0.0
...                               ...      ...        ...           ...
2026-06-12 00:00:00-04:00  226.210007  2189800        1.7           0.0
2026-06-15 00:00:00-04:00  223.220001  2314700        0.0           0.0
2026-06-16 00:00:00-04:00  222.000000  2615400        0.0           0.0
2026-06-17 00:00:00-04:00  218.759995  2743300        0.0           0.0
2026-06-18 00:00:00-04:00  217.845001  1045850        0.0           0.0

[3386 rows x 8 columns], 'AFL':                                  Open        High         Low       Close  \
Date
2013-01-02 00:00:00-05:00   27.195000   27.219999   26.860001   27.035000
2013-01-03 00:00:00-05:00   26.809999   26.809999   26.055000   26.350000
2013-01-04 00:00:00-05:00   26.440001   26.570000   26.004999   26.020000
2013-01-07 00:00:00-05:00   25.910000   25.934999   25.545000   25.920000
2013-01-08 00:00:00-05:00   25.834999   26.219999   25.764999   26.219999
...                               ...         ...         ...         ...
2026-06-12 00:00:00-04:00  116.550003  118.389999  115.660004  117.800003
2026-06-15 00:00:00-04:00  117.080002  118.099998  116.660004  116.959999
2026-06-16 00:00:00-04:00  117.720001  118.300003  116.480003  117.410004
2026-06-17 00:00:00-04:00  116.760002  117.570000  116.199997  116.239998
2026-06-18 00:00:00-04:00  117.250000  117.250000  114.769997  114.925003

                            Adj Close    Volume  Dividends  Stock Splits
Date
2013-01-02 00:00:00-05:00   19.635553   8072800        0.0           0.0
2013-01-03 00:00:00-05:00   19.138039  10289000        0.0           0.0
2013-01-04 00:00:00-05:00   18.898357   8746400        0.0           0.0
2013-01-07 00:00:00-05:00   18.825726   9042200        0.0           0.0
2013-01-08 00:00:00-05:00   19.043621   6733600        0.0           0.0
...                               ...       ...        ...           ...
2026-06-12 00:00:00-04:00  117.800003   2576900        0.0           0.0
2026-06-15 00:00:00-04:00  116.959999   2439200        0.0           0.0
2026-06-16 00:00:00-04:00  117.410004   3578500        0.0           0.0
2026-06-17 00:00:00-04:00  116.239998   3504400        0.0           0.0
2026-06-18 00:00:00-04:00  114.925003   1072349        0.0           0.0

[3386 rows x 8 columns], 'ALB':                                  Open        High         Low       Close  \
Date
2013-01-02 00:00:00-05:00   63.689999   64.720001   63.689999   64.300003
2013-01-03 00:00:00-05:00   64.330002   64.699997   63.570000   63.880001
2013-01-04 00:00:00-05:00   63.820000   64.809998   63.779999   64.629997
2013-01-07 00:00:00-05:00   64.120003   65.080002   64.000000   64.949997
2013-01-08 00:00:00-05:00   64.400002   64.589996   63.520000   63.770000
...                               ...         ...         ...         ...
2026-06-12 00:00:00-04:00  161.580002  174.330002  161.580002  170.419998
2026-06-15 00:00:00-04:00  171.759995  173.259995  165.500000  168.899994
2026-06-16 00:00:00-04:00  167.660004  170.490005  165.339996  166.110001
2026-06-17 00:00:00-04:00  167.850006  171.000000  165.809998  166.559998
2026-06-18 00:00:00-04:00  167.600006  168.820007  159.300003  159.679993

                            Adj Close   Volume  Dividends  Stock Splits
Date
2013-01-02 00:00:00-05:00   52.796516   568100      0.000           0.0
2013-01-03 00:00:00-05:00   52.451668   408000      0.000           0.0
2013-01-04 00:00:00-05:00   53.067471   441300      0.000           0.0
2013-01-07 00:00:00-05:00   53.330235   668600      0.000           0.0
2013-01-08 00:00:00-05:00   52.361336   318000      0.000           0.0
...                               ...      ...        ...           ...
2026-06-12 00:00:00-04:00  170.419998  3265100      0.405           0.0
2026-06-15 00:00:00-04:00  168.899994  2843400      0.000           0.0
2026-06-16 00:00:00-04:00  166.110001  1497900      0.000           0.0
2026-06-17 00:00:00-04:00  166.559998  2682200      0.000           0.0
2026-06-18 00:00:00-04:00  159.679993  1364635      0.000           0.0

[3386 rows x 8 columns], 'AMCR':                                 Open       High        Low      Close  \
Date
2013-01-02 00:00:00-05:00  41.849998  41.849998  41.849998  41.849998
2013-01-03 00:00:00-05:00  41.849998  41.849998  41.849998  41.849998
2013-01-04 00:00:00-05:00  41.849998  41.849998  41.849998  41.849998
2013-01-07 00:00:00-05:00  43.299999  43.299999  43.299999  43.299999
2013-01-08 00:00:00-05:00  43.299999  43.299999  43.299999  43.299999
...                              ...        ...        ...        ...
2026-06-12 00:00:00-04:00  40.599998  40.950001  40.189999  40.599998
2026-06-15 00:00:00-04:00  41.650002  42.320000  41.110001  41.110001
2026-06-16 00:00:00-04:00  41.139999  41.660000  40.980000  41.419998
2026-06-17 00:00:00-04:00  41.150002  41.900002  40.490002  40.770000
2026-06-18 00:00:00-04:00  41.119999  41.830002  40.930000  41.540001

                           Adj Close   Volume  Dividends  Stock Splits
Date
2013-01-02 00:00:00-05:00  24.865166        0        0.0           0.0
2013-01-03 00:00:00-05:00  24.865166        0        0.0           0.0
2013-01-04 00:00:00-05:00  24.865166        0        0.0           0.0
2013-01-07 00:00:00-05:00  25.726679       40        0.0           0.0
2013-01-08 00:00:00-05:00  25.726679        0        0.0           0.0
...                              ...      ...        ...           ...
2026-06-12 00:00:00-04:00  40.599998  2976200        0.0           0.0
2026-06-15 00:00:00-04:00  41.110001  3393800        0.0           0.0
2026-06-16 00:00:00-04:00  41.419998  3100900        0.0           0.0
2026-06-17 00:00:00-04:00  40.770000  4064400        0.0           0.0
2026-06-18 00:00:00-04:00  41.540001  1527461        0.0           0.0

[3386 rows x 8 columns], 'AOS':                                 Open       High        Low      Close  \
Date
2013-01-02 00:00:00-05:00  16.102501  16.432501  16.042500  16.152500
2013-01-03 00:00:00-05:00  15.835000  16.007500  15.502500  15.900000
2013-01-04 00:00:00-05:00  15.985000  16.092501  15.787500  16.072500
2013-01-07 00:00:00-05:00  15.975000  16.202499  15.805000  15.895000
2013-01-08 00:00:00-05:00  15.915000  16.232500  15.867500  16.197500
...                              ...        ...        ...        ...
2026-06-12 00:00:00-04:00  59.150002  59.619999  58.419998  59.080002
2026-06-15 00:00:00-04:00  60.060001  60.849998  59.630001  60.020000
2026-06-16 00:00:00-04:00  60.220001  61.230000  60.169998  60.240002
2026-06-17 00:00:00-04:00  60.139999  60.799999  57.720001  57.880001
2026-06-18 00:00:00-04:00  58.970001  60.075001  58.900002  59.590000

                           Adj Close   Volume  Dividends  Stock Splits
Date
2013-01-02 00:00:00-05:00  13.080873  2003600        0.0           0.0
2013-01-03 00:00:00-05:00  12.876384  2563200        0.0           0.0
2013-01-04 00:00:00-05:00  13.016086  1258800        0.0           0.0
2013-01-07 00:00:00-05:00  12.872339  1925600        0.0           0.0
2013-01-08 00:00:00-05:00  13.117316  1866800        0.0           0.0
...                              ...      ...        ...           ...
2026-06-12 00:00:00-04:00  59.080002  1646700        0.0           0.0
2026-06-15 00:00:00-04:00  60.020000  1848000        0.0           0.0
2026-06-16 00:00:00-04:00  60.240002  1342200        0.0           0.0
2026-06-17 00:00:00-04:00  57.880001  1835100        0.0           0.0
2026-06-18 00:00:00-04:00  59.590000   606652        0.0           0.0

[3386 rows x 8 columns], 'APD':                                  Open        High         Low       Close  \
Date
2013-01-02 00:00:00-05:00   79.056427   79.500465   78.667900   79.426460
2013-01-03 00:00:00-05:00   79.518967   79.925995   78.936172   79.148933
2013-01-04 00:00:00-05:00   79.426460   80.305275   79.269196   80.212769
2013-01-07 00:00:00-05:00   79.907494   80.222015   79.315453   80.138763
2013-01-08 00:00:00-05:00   80.092506   80.305275   79.121185   80.286774
...                               ...         ...         ...         ...
2026-06-12 00:00:00-04:00  280.000000  287.070007  279.570007  281.619995
2026-06-15 00:00:00-04:00  280.010010  283.989990  276.660004  282.959991
2026-06-16 00:00:00-04:00  283.070007  284.850006  278.290009  280.480011
2026-06-17 00:00:00-04:00  279.489990  283.579987  279.359985  281.750000
2026-06-18 00:00:00-04:00  283.399994  283.834991  279.614990  280.920013

                            Adj Close   Volume  Dividends  Stock Splits
Date
2013-01-02 00:00:00-05:00   57.314999  1312875        0.0           0.0
2013-01-03 00:00:00-05:00   57.114738   766321        0.0           0.0
2013-01-04 00:00:00-05:00   57.882416  1051813        0.0           0.0
2013-01-07 00:00:00-05:00   57.828987   898743        0.0           0.0
2013-01-08 00:00:00-05:00   57.935814  1425839        0.0           0.0
...                               ...      ...        ...           ...
2026-06-12 00:00:00-04:00  281.619995  1239500        0.0           0.0
2026-06-15 00:00:00-04:00  282.959991  1164500        0.0           0.0
2026-06-16 00:00:00-04:00  280.480011  1859200        0.0           0.0
2026-06-17 00:00:00-04:00  281.750000  1748100        0.0           0.0
2026-06-18 00:00:00-04:00  280.920013   689829        0.0           0.0

[3386 rows x 8 columns], 'ATO':                                  Open        High         Low       Close  \
Date
2013-01-02 00:00:00-05:00   35.610001   35.860001   35.529999   35.770000
2013-01-03 00:00:00-05:00   35.720001   35.990002   35.459999   35.590000
2013-01-04 00:00:00-05:00   35.639999   36.029999   35.470001   35.939999
2013-01-07 00:00:00-05:00   35.790001   35.849998   35.049999   35.110001
2013-01-08 00:00:00-05:00   35.040001   35.299999   34.869999   35.180000
...                               ...         ...         ...         ...
2026-06-12 00:00:00-04:00  168.220001  169.990005  167.770004  169.960007
2026-06-15 00:00:00-04:00  168.820007  170.850006  168.399994  169.600006
2026-06-16 00:00:00-04:00  170.190002  171.279999  168.929993  169.630005
2026-06-17 00:00:00-04:00  168.619995  170.050003  168.220001  169.639999
2026-06-18 00:00:00-04:00  169.639999  171.184998  169.639999  170.639999

                            Adj Close   Volume  Dividends  Stock Splits
Date
2013-01-02 00:00:00-05:00   25.444189   367500        0.0           0.0
2013-01-03 00:00:00-05:00   25.316154   328300        0.0           0.0
2013-01-04 00:00:00-05:00   25.565109   408800        0.0           0.0
2013-01-07 00:00:00-05:00   24.974707   424200        0.0           0.0
2013-01-08 00:00:00-05:00   25.024500   360700        0.0           0.0
...                               ...      ...        ...           ...
2026-06-12 00:00:00-04:00  169.960007  1540700        0.0           0.0
2026-06-15 00:00:00-04:00  169.600006  1576900        0.0           0.0
2026-06-16 00:00:00-04:00  169.630005  1027900        0.0           0.0
2026-06-17 00:00:00-04:00  169.639999  1480000        0.0           0.0
2026-06-18 00:00:00-04:00  170.639999   554218        0.0           0.0

[3386 rows x 8 columns], 'BDX':                                  Open        High         Low       Close  \
Date
2013-01-02 00:00:00-05:00   60.791531   60.937260   60.385029   60.937260
2013-01-03 00:00:00-05:00   61.282406   61.934345   61.098328   61.658230
2013-01-04 00:00:00-05:00   61.811626   61.819298   61.489491   61.627548
2013-01-07 00:00:00-05:00   61.481823   62.118423   61.474152   61.834637
2013-01-08 00:00:00-05:00   61.857647   62.394539   61.259396   62.386868
...                               ...         ...         ...         ...
2026-06-12 00:00:00-04:00  147.940002  149.000000  144.399994  146.240005
2026-06-15 00:00:00-04:00  146.600006  147.940002  145.440002  145.520004
2026-06-16 00:00:00-04:00  146.570007  146.889999  144.259995  145.160004
2026-06-17 00:00:00-04:00  144.500000  145.600006  140.630005  141.610001
2026-06-18 00:00:00-04:00  142.020004  143.957001  141.744995  143.729996

                            Adj Close   Volume  Dividends  Stock Splits
Date
2013-01-02 00:00:00-05:00   48.906216  1318533        0.0           0.0
2013-01-03 00:00:00-05:00   49.484837  1530922        0.0           0.0
2013-01-04 00:00:00-05:00   49.460201  1153081        0.0           0.0
2013-01-07 00:00:00-05:00   49.626400  1060120        0.0           0.0
2013-01-08 00:00:00-05:00   50.069614  1529618        0.0           0.0
...                               ...      ...        ...           ...
2026-06-12 00:00:00-04:00  146.240005  1966900        0.0           0.0
2026-06-15 00:00:00-04:00  145.520004  1760200        0.0           0.0
2026-06-16 00:00:00-04:00  145.160004  1509900        0.0           0.0
2026-06-17 00:00:00-04:00  141.610001  2920800        0.0           0.0
2026-06-18 00:00:00-04:00  143.729996  1192162        0.0           0.0

[3386 rows x 8 columns], 'BEN':                                 Open       High        Low      Close  \
Date
2013-01-02 00:00:00-05:00  42.866669  43.326668  42.669998  43.323334
2013-01-03 00:00:00-05:00  43.363335  43.533333  43.056667  43.263332
2013-01-04 00:00:00-05:00  43.393333  43.866669  43.286667  43.823334
2013-01-07 00:00:00-05:00  43.523335  43.736668  43.376667  43.509998

In [25]:
# Unfortunately yfinance doesn't have a way to return the S&P 500 
# sector indices as a list; therefore, I will need to manually create 
# a dictionary for the relevant general market and sector indices, 
# as well as the NOBL exchange-traded fund (ETF) benchark that will be 
# used for the time series machine learning.
indices_dict = {
    'Ticker': ['NOBL', 
                      '^GSPC',
					  '^SP500-15', 
					  '^SP500-50', 
					  '^GSPE', 
					  '^SP500-40', 
					  '^SP500-20', 
					  '^SP500-45', 
					  '^SP500-30', 
					  '^SP500-60',
					  '^SP500-55',
					  '^SP500-35',
					  '^SP500-25'],
    'Name': ['S&P 500 Dividend Aristocrats ETF',
             'S&P 500 Index',
	         'S&P 500 Materials Sector Index',
			 'S&P 500 Communication Sector Index',
			 'S&P 500 Energy Sector Index',
			 'S&P 500 Financials Sector Index',
			 'S&P 500 Industrial Sector Index',
			 'S&P 500 Technology Sector Index',
			 'S&P 500 Consumer Staples Sector Index',
			 'S&P 500 Real Estate Sector Index',
			 'S&P 500 Utilities Sector Index',
			 'S&P 500 Health Care Sector Index',
			 'S&P 500 Consumer Discretionary Sector Index'],
    'Type': ['ETF',
             'Index',
             'Index',
             'Index',
             'Index',
             'Index',
             'Index',
             'Index',
             'Index',
             'Index',
             'Index',
             'Index',
             'Index'],
    'Sector': ['NA', 
               'NA',
	           'Materials', 
			   'Communication Services',
			   'Energy',
			   'Financials',
			   'Industrials',
			   'Information Technology',
			   'Consumer Staples',
			   'Real Estate',
			   'Utilities',
			   'Health Care',
			   'Consumer Discretionary']
}

# Convert to DataFrame
indices = pd.DataFrame(indices_dict)
indices

,Ticker,Name,Type,Sector
0,NOBL,S&P 500 Dividend Aristocrats ETF,ETF,NA
1,^GSPC,S&P 500 Index,Index,NA
2,^SP500-15,S&P 500 Materials Sector Index,Index,Materials
3,^SP500-50,S&P 500 Communication Sector Index,Index,Communication Services
4,^GSPE,S&P 500 Energy Sector Index,Index,Energy
5,^SP500-40,S&P 500 Financials Sector Index,Index,Financials
6,^SP500-20,S&P 500 Industrial Sector Index,Index,Industrials
7,^SP500-45,S&P 500 Technology Sector Index,Index,Information Technology
8,^SP500-30,S&P 500 Consumer Staples Sector Index,Index,Consumer Staples
9,^SP500-60,S&P 500 Real Estate Sector Index,Index,Real Estate
10,^SP500-55,S&P 500 Utilities Sector Index,Index,Utilities
11,^SP500-35,S&P 500 Health Care Sector Index,Index,Health Care
12,^SP500-25,S&P 500 Consumer Discretionary Sector Index,Index,Consumer Discretionary

In [26]:
# Iterate through the aristocrats_complete DataFrame and fetch
# historical price and dividend data since 1/1/2013.
index_symbols = indices['Ticker']
index_data = {
    symbol: yf.Ticker(symbol).history(start='2013-01-01', auto_adjust=False) for symbol in index_symbols
}
print("Done")

# Quick look at dictionary of index data
print(index_data)

Done
{'NOBL':                                 Open       High        Low      Close  \
Date
2013-10-10 00:00:00-04:00  20.200001  20.459999  20.200001  20.375000
2013-10-11 00:00:00-04:00  20.745001  20.745001  20.350000  20.520000
2013-10-14 00:00:00-04:00  20.424999  20.605000  20.405001  20.590000
2013-10-15 00:00:00-04:00  20.555000  20.559999  20.415001  20.434999
2013-10-16 00:00:00-04:00  20.605000  20.660000  20.495001  20.639999
...                              ...        ...        ...        ...
2026-06-12 00:00:00-04:00  55.500000  55.750000  55.310001  55.630001
2026-06-15 00:00:00-04:00  55.730000  55.880001  55.549999  55.590000
2026-06-16 00:00:00-04:00  55.740002  56.080002  55.610001  55.820000
2026-06-17 00:00:00-04:00  55.799999  55.840000  54.740002  54.869999
2026-06-18 00:00:00-04:00  55.169998  55.220001  54.980000  55.029999

                           Adj Close   Volume  Dividends  Stock Splits  \
Date
2013-10-10 00:00:00-04:00  15.756350    36000        0.0           0.0
2013-10-11 00:00:00-04:00  15.868479   163800        0.0           0.0
2013-10-14 00:00:00-04:00  15.922612   167200        0.0           0.0
2013-10-15 00:00:00-04:00  15.802752    99000        0.0           0.0
2013-10-16 00:00:00-04:00  15.961281   115600        0.0           0.0
...                              ...      ...        ...           ...
2026-06-12 00:00:00-04:00  55.630001   874300        0.0           0.0
2026-06-15 00:00:00-04:00  55.590000   927600        0.0           0.0
2026-06-16 00:00:00-04:00  55.820000  1085500        0.0           0.0
2026-06-17 00:00:00-04:00  54.869999  1518100        0.0           0.0
2026-06-18 00:00:00-04:00  55.029999   589319        0.0           0.0

                           Capital Gains
Date
2013-10-10 00:00:00-04:00            0.0
2013-10-11 00:00:00-04:00            0.0
2013-10-14 00:00:00-04:00            0.0
2013-10-15 00:00:00-04:00            0.0
2013-10-16 00:00:00-04:00            0.0
...                                  ...
2026-06-12 00:00:00-04:00            0.0
2026-06-15 00:00:00-04:00            0.0
2026-06-16 00:00:00-04:00            0.0
2026-06-17 00:00:00-04:00            0.0
2026-06-18 00:00:00-04:00            0.0

[3191 rows x 9 columns], '^GSPC':                                   Open         High          Low        Close  \
Date
2013-01-02 00:00:00-05:00  1426.189941  1462.430054  1426.189941  1462.420044
2013-01-03 00:00:00-05:00  1462.420044  1465.469971  1455.530029  1459.369995
2013-01-04 00:00:00-05:00  1459.369995  1467.939941  1458.989990  1466.469971
2013-01-07 00:00:00-05:00  1466.469971  1466.469971  1456.619995  1461.890015
2013-01-08 00:00:00-05:00  1461.890015  1461.890015  1451.640015  1457.150024
...                                ...          ...          ...          ...
2026-06-12 00:00:00-04:00  7410.850098  7456.399902  7363.009766  7431.459961
2026-06-15 00:00:00-04:00  7516.750000  7577.919922  7516.750000  7554.290039
2026-06-16 00:00:00-04:00  7548.779785  7564.959961  7508.680176  7511.350098
2026-06-17 00:00:00-04:00  7524.500000  7532.169922  7402.609863  7420.100098
2026-06-18 00:00:00-04:00  7487.359863  7509.439941  7468.319824  7505.569824

                             Adj Close      Volume  Dividends  Stock Splits
Date
2013-01-02 00:00:00-05:00  1462.420044  4202600000        0.0           0.0
2013-01-03 00:00:00-05:00  1459.369995  3829730000        0.0           0.0
2013-01-04 00:00:00-05:00  1466.469971  3424290000        0.0           0.0
2013-01-07 00:00:00-05:00  1461.890015  3304970000        0.0           0.0
2013-01-08 00:00:00-05:00  1457.150024  3601600000        0.0           0.0
...                                ...         ...        ...           ...
2026-06-12 00:00:00-04:00  7431.459961  4950530000        0.0           0.0
2026-06-15 00:00:00-04:00  7554.290039  5674670000        0.0           0.0
2026-06-16 00:00:00-04:00  7511.350098  5286210000        0.0           0.0
2026-06-17 00:00:00-04:00  7420.100098  5883740000        0.0           0.0
2026-06-18 00:00:00-04:00  7505.569824  1916427000        0.0           0.0

[3386 rows x 8 columns], '^SP500-15':                                  Open        High         Low       Close  \
Date
2013-01-02 00:00:00-05:00  237.520004  244.050003  237.520004  243.210007
2013-01-03 00:00:00-05:00  243.210007  243.979996  241.529999  242.190002
2013-01-04 00:00:00-05:00  241.550003  244.679993  241.550003  244.389999
2013-01-07 00:00:00-05:00  244.389999  244.389999  242.570007  243.899994
2013-01-08 00:00:00-05:00  243.899994  244.690002  242.580002  244.339996
...                               ...         ...         ...         ...
2026-06-09 00:00:00-04:00  630.669983  634.349976  622.539978  633.650024
2026-06-10 00:00:00-04:00  631.000000  634.619995  617.799988  618.119995
2026-06-11 00:00:00-04:00  623.969971  639.849976  623.739990  638.270020
2026-06-12 00:00:00-04:00  646.190002  652.070007  641.929993  649.960022
2026-06-18 00:00:00-04:00  651.119995  655.250000  649.539978  651.190002

                            Adj Close     Volume  Dividends  Stock Splits
Date
2013-01-02 00:00:00-05:00  243.210007  133782600        0.0           0.0
2013-01-03 00:00:00-05:00  242.190002   75962800        0.0           0.0
2013-01-04 00:00:00-05:00  244.389999   98222000        0.0           0.0
2013-01-07 00:00:00-05:00  243.899994   95048200        0.0           0.0
2013-01-08 00:00:00-05:00  244.339996  125488100        0.0           0.0
...                               ...        ...        ...           ...
2026-06-09 00:00:00-04:00  633.650024  109726700        0.0           0.0
2026-06-10 00:00:00-04:00  618.119995  109199100        0.0           0.0
2026-06-11 00:00:00-04:00  638.270020  116757400        0.0           0.0
2026-06-12 00:00:00-04:00  649.960022  106275300        0.0           0.0
2026-06-18 00:00:00-04:00  651.190002   57847985        0.0           0.0

[3383 rows x 8 columns], '^SP500-50':                                  Open        High         Low       Close  \
Date
2013-01-02 00:00:00-05:00  146.039993  150.679993  146.039993  150.679993
2013-01-03 00:00:00-05:00  150.679993  150.889999  149.520004  150.330002
2013-01-04 00:00:00-05:00  150.300003  151.330002  150.020004  151.229996
2013-01-07 00:00:00-05:00  151.229996  152.440002  150.710007  152.089996
2013-01-08 00:00:00-05:00  150.580002  150.580002  147.759995  148.000000
...                               ...         ...         ...         ...
2026-06-09 00:00:00-04:00  472.869995  476.739990  463.609985  469.510010
2026-06-10 00:00:00-04:00  468.750000  473.459991  461.269989  461.779999
2026-06-11 00:00:00-04:00  460.950012  464.399994  451.959991  463.350006
2026-06-12 00:00:00-04:00  468.399994  471.170013  459.429993  464.890015
2026-06-18 00:00:00-04:00  467.070007  469.570007  460.109985  469.230011

                            Adj Close     Volume  Dividends  Stock Splits
Date
2013-01-02 00:00:00-05:00  150.679993  155311800        0.0           0.0
2013-01-03 00:00:00-05:00  150.330002   79931800        0.0           0.0
2013-01-04 00:00:00-05:00  151.229996  131654200        0.0           0.0
2013-01-07 00:00:00-05:00  152.089996  108998800        0.0           0.0
2013-01-08 00:00:00-05:00  148.000000  149085400        0.0           0.0
...                               ...        ...        ...           ...
2026-06-09 00:00:00-04:00  469.510010  301028900        0.0           0.0
2026-06-10 00:00:00-04:00  461.779999  278114100        0.0           0.0
2026-06-11 00:00:00-04:00  463.350006  302609400        0.0           0.0
2026-06-12 00:00:00-04:00  464.890015  318800400        0.0           0.0
2026-06-18 00:00:00-04:00  469.230011  175073022        0.0           0.0

[3380 rows x 8 columns], '^GSPE':                                  Open        High         Low       Close  \
Date
2013-01-02 00:00:00-05:00  532.960022  545.440002  532.960022  545.390015
2013-01-03 00:00:00-05:00  545.390015  549.070007  542.260010  545.330017
2013-01-04 00:00:00-05:00  544.849976  551.119995  544.849976  550.559998
2013-01-07 00:00:00-05:00  550.559998  550.559998  544.020020  546.059998
2013-01-08 00:00:00-05:00  546.059998  546.059998  541.419983  545.190002
...                               ...         ...         ...         ...
2026-06-09 00:00:00-04:00  884.830017  884.830017  863.650024  871.770020
2026-06-10 00:00:00-04:00  880.080017  896.330017  878.869995  884.520020
2026-06-11 00:00:00-04:00  895.190002  895.559998  865.679993  866.330017
2026-06-12 00:00:00-04:00  861.650024  881.479980  858.929993  872.609985
2026-06-18 00:00:00-04:00  818.750000  819.059998  807.380005  812.429993

                            Adj Close     Volume  Dividends  Stock Splits
Date
2013-01-02 00:00:00-05:00  545.390015  201635400        0.0           0.0
2013-01-03 00:00:00-05:00  545.330017  123108800        0.0           0.0
2013-01-04 00:00:00-05:00  550.559998  157331400        0.0           0.0
2013-01-07 00:00:00-05:00  546.059998  165848300        0.0           0.0
2013-01-08 00:00:00-05:00  545.190002  182595800        0.0           0.0
...                               ...        ...        ...           ...
2026-06-09 00:00:00-04:00  871.770020  132969500        0.0           0.0
2026-06-10 00:00:00-04:00  884.520020  125301700        0.0           0.0
2026-06-11 00:00:00-04:00  866.330017  141696900        0.0           0.0
2026-06-12 00:00:00-04:00  872.609985  128526400        0.0           0.0
2026-06-18 00:00:00-04:00  812.429993   95934414        0.0           0.0

[3383 rows x 8 columns], '^SP500-40':                                  Open        High         Low       Close  \
Date
2013-01-02 00:00:00-05:00  221.080002  227.619995  221.080002  227.610001
2013-01-03 00:00:00-05:00  227.610001  227.860001  226.289993  227.440002
2013-01-04 00:00:00-05:00  227.229996  230.210007  227.169998  230.089996
2013-01-07 00:00:00-05:00  230.089996  230.089996  228.179993  229.339996
2013-01-08 00:00:00-05:00  229.330002  229.330002  227.580002  228.740005
...                               ...         ...         ...         ...
2026-06-09 00:00:00-04:00  864.590027  874.479980  863.840027  871.119995
2026-06-10 00:00:00-04:00  871.750000  876.409973  866.690002  866.760010
2026-06-11 00:00:00-04:00  868.429993  875.700012  863.969971  873.570007
2026-06-12 00:00:00-04:00  879.510010  888.510010  877.289978  885.400024
2026-06-18 00:00:00-04:00  905.349976  905.349976  890.000000  891.820007

                            Adj Close     Volume  Dividends  Stock Splits
Date
2013-01-02 00:00:00-05:00  227.610001    7198000        0.0           0.0
2013-01-03 00:00:00-05:00  227.440002    4251800        0.0           0.0
2013-01-04 00:00:00-05:00  230.089996    5817600        0.0           0.0
2013-01-07 00:00:00-05:00  229.339996    5601800        0.0           0.0
2013-01-08 00:00:00-05:00  228.740005    5427100        0.0           0.0
...                               ...        ...        ...           ...
2026-06-09 00:00:00-04:00  871.119995  392692700        0.0           0.0
2026-06-10 00:00:00-04:00  866.760010  379673000        0.0           0.0
2026-06-11 00:00:00-04:00  873.570007  371888800        0.0           0.0
2026-06-12 00:00:00-04:00  885.400024  333918600        0.0           0.0
2026-06-18 00:00:00-04:00  891.820007  201382620        0.0           0.0

[3380 rows x 8 columns], '^SP500-20':                                   Open         High          Low        Close  \
Date
2013-01-02 00:00:00-05:00   328.739990   337.130005   328.739990   336.510010
2013-01-03 00:00:00-05:00   336.510010   338.500000   336.200012   336.980011
2013-01-04 00:00:00-05:00   336.380005   339.040009   336.380005   338.779999
2013-01-07 00:00:00-05:00   338.779999   338.779999   336.239990   337.489990
2013-01-08 00:00:00-05:00   337.489990   337.489990   333.609985   334.829987
...                                ...          ...          ...          ...
2026-06-09 00:00:00-04:00  1474.510010  1491.650024  1451.520020  1483.989990
2026-06-10 00:00:00-04:00  1474.160034  1474.160034  1432.030029  1433.329956
2026-06-11 00:00:00-04:00  1445.699951  1484.130005  1444.959961  1479.930054
2026-06-12 00:00:00-04:00  1488.010010  1491.489990  1475.199951  1488.489990
2026-06-18 00:00:00-04:00  1539.869995  1544.030029  1525.189941  1533.310059

                             Adj Close     Volume  Dividends  Stock Splits
Date
2013-01-02 00:00:00-05:00   336.510010    2099000        0.0           0.0
2013-01-03 00:00:00-05:00   336.980011    1245400        0.0           0.0
2013-01-04 00:00:00-05:00   338.779999    1472800        0.0           0.0
2013-01-07 00:00:00-05:00   337.489990    1529600        0.0           0.0
2013-01-08 00:00:00-05:00   334.829987    1805500        0.0           0.0
...                                ...        ...        ...           ...
2026-06-09 00:00:00-04:00  1483.989990  225089700        0.0           0.0
2026-06-10 00:00:00-04:00  1433.329956  222592100        0.0           0.0
2026-06-11 00:00:00-04:00  1479.930054  218300800        0.0           0.0
2026-06-12 00:00:00-04:00  1488.489990  182348800        0.0           0.0
2026-06-18 00:00:00-04:00  1533.310059  105082260        0.0           0.0

[3380 rows x 8 columns], '^SP500-45':                                   Open         High          Low        Close  \
Date
2013-01-02 00:00:00-05:00   463.820007   478.410004   463.820007   478.410004
2013-01-03 00:00:00-05:00   478.410004   479.119995   475.429993   476.149994
2013-01-04 00:00:00-05:00   474.899994   474.929993   470.790009   472.260010
2013-01-07 00:00:00-05:00   472.250000   472.579987   468.529999   471.200012
2013-01-08 00:00:00-05:00   471.200012   472.579987   467.290009   470.010010
...                                ...          ...          ...          ...
2026-06-09 00:00:00-04:00  6782.660156  6813.250000  6366.459961  6616.390137
2026-06-10 00:00:00-04:00  6531.069824  6635.220215  6453.080078  6461.859863
2026-06-11 00:00:00-04:00  6501.359863  6662.250000  6442.990234  6651.750000
2026-06-12 00:00:00-04:00  6627.500000  6709.790039  6589.720215  6676.549805
2026-06-18 00:00:00-04:00  6830.979980  6877.520020  6806.049805  6876.779785

                             Adj Close      Volume  Dividends  Stock Splits
Date
2013-01-02 00:00:00-05:00   478.410004     6772000        0.0           0.0
2013-01-03 00:00:00-05:00   476.149994     4384600        0.0           0.0
2013-01-04 00:00:00-05:00   472.260010     5059400        0.0           0.0
2013-01-07 00:00:00-05:00   471.200012     5111100        0.0           0.0
2013-01-08 00:00:00-05:00   470.010010     5588600        0.0           0.0
...                                ...         ...        ...           ...
2026-06-09 00:00:00-04:00  6616.390137  1127002600        0.0           0.0
2026-06-10 00:00:00-04:00  6461.859863  1102483100        0.0           0.0
2026-06-11 00:00:00-04:00  6651.750000  1294589800        0.0           0.0
2026-06-12 00:00:00-04:00  6676.549805   921523600        0.0           0.0
2026-06-18 00:00:00-04:00  6876.779785   677758361        0.0           0.0

[3380 rows x 8 columns], '^SP500-30':                                  Open        High         Low       Close  \
Date
2013-01-02 00:00:00-05:00  360.739990  370.279999  360.739990  370.279999
2013-01-03 00:00:00-05:00  370.279999  370.299988  368.420013  369.369995
2013-01-04 00:00:00-05:00  369.149994  370.720001  368.910004  370.350006
2013-01-07 00:00:00-05:00  370.350006  370.350006  367.019989  367.899994
2013-01-08 00:00:00-05:00  367.850006  367.850006  366.380005  367.029999
...                               ...         ...         ...         ...
2026-06-09 00:00:00-04:00  927.440002  943.159973  924.460022  936.479980
2026-06-10 00:00:00-04:00  944.000000  953.349976  938.580017  952.299988
2026-06-11 00:00:00-04:00  955.150024  957.830017  947.179993  947.780029
2026-06-12 00:00:00-04:00  950.950012  954.320007  946.340027  954.289978
2026-06-18 00:00:00-04:00  931.599976  933.349976  927.700012  928.840027

                            Adj Close     Volume  Dividends  Stock Splits
Date
2013-01-02 00:00:00-05:00  370.279999  190795400        0.0           0.0
2013-01-03 00:00:00-05:00  369.369995  111642600        0.0           0.0
2013-01-04 00:00:00-05:00  370.350006  141927400        0.0           0.0
2013-01-07 00:00:00-05:00  367.899994  146582900        0.0           0.0
2013-01-08 00:00:00-05:00  367.029999  153653900        0.0           0.0
...                               ...        ...        ...           ...
2026-06-09 00:00:00-04:00  936.479980  247055600        0.0           0.0
2026-06-10 00:00:00-04:00  952.299988  234197700        0.0           0.0
2026-06-11 00:00:00-04:00  947.780029  218004100        0.0           0.0
2026-06-12 00:00:00-04:00  954.289978  183935300        0.0           0.0
2026-06-18 00:00:00-04:00  928.840027  123330254        0.0           0.0

[3380 rows x 8 columns], '^SP500-60':                                  Open        High         Low       Close  \
Date
2013-01-02 00:00:00-05:00  151.380005  153.669998  151.380005  153.350006
2013-01-03 00:00:00-05:00  153.130005  153.729996  152.630005  152.899994
2013-01-04 00:00:00-05:00  152.960007  153.669998  152.740005  153.630005
2013-01-07 00:00:00-05:00  153.520004  154.059998  153.179993  153.919998
2013-01-08 00:00:00-05:00  153.919998  154.149994  153.199997  153.770004
...                               ...         ...         ...         ...
2026-06-12 00:00:00-04:00  285.649994  287.929993  285.420013  287.010010
2026-06-15 00:00:00-04:00  286.040009  288.380005  283.779999  284.420013
2026-06-16 00:00:00-04:00  285.660004  287.130005  284.140015  284.920013
2026-06-17 00:00:00-04:00  283.940002  284.670013  277.220001  277.890015
2026-06-18 00:00:00-04:00  279.940002  279.940002  278.140015  278.869995

                            Adj Close     Volume  Dividends  Stock Splits
Date
2013-01-02 00:00:00-05:00  153.350006   40613100        0.0           0.0
2013-01-03 00:00:00-05:00  152.899994   39340400        0.0           0.0
2013-01-04 00:00:00-05:00  153.630005   33317900        0.0           0.0
2013-01-07 00:00:00-05:00  153.919998          0        0.0           0.0
2013-01-08 00:00:00-05:00  153.770004          0        0.0           0.0
...                               ...        ...        ...           ...
2026-06-12 00:00:00-04:00  287.010010   91200800        0.0           0.0
2026-06-15 00:00:00-04:00  284.420013  114295700        0.0           0.0
2026-06-16 00:00:00-04:00  284.920013   94215400        0.0           0.0
2026-06-17 00:00:00-04:00  277.890015  102727400        0.0           0.0
2026-06-18 00:00:00-04:00  278.869995   51788241        0.0           0.0

[3386 rows x 8 columns], '^SP500-55':                                  Open        High         Low       Close  \
Date
2013-01-02 00:00:00-05:00  177.660004  181.100006  177.660004  180.880005
2013-01-03 00:00:00-05:00  180.880005  181.490005  180.449997  181.009995
2013-01-04 00:00:00-05:00  180.880005  181.919998  180.880005  181.860001
2013-01-07 00:00:00-05:00  181.860001  181.860001  179.610001  179.779999
2013-01-08 00:00:00-05:00  179.779999  179.809998  178.770004  179.449997
...                               ...         ...         ...         ...
2026-06-09 00:00:00-04:00  441.279999  445.339996  439.299988  444.670013
2026-06-10 00:00:00-04:00  446.350006  446.529999  442.500000  444.640015
2026-06-11 00:00:00-04:00  447.070007  449.700012  444.709991  444.959991
2026-06-12 00:00:00-04:00  446.809998  450.630005  446.809998  449.950012
2026-06-18 00:00:00-04:00  450.709991  457.950012  450.529999  455.230011

                            Adj Close     Volume  Dividends  Stock Splits
Date
2013-01-02 00:00:00-05:00  180.880005   91658800        0.0           0.0

In [27]:
# Create function to standardize price and dividend data for all asset classes
# used in the analysis (stocks, ETFs, and indexes).
def standardize_data(data_dict):
    standardized = []
    for symbol, df in data_dict.items():
        if not df.empty:
            df = df[["Open", "High", "Low", "Close", "Adj Close", "Volume", "Dividends", "Stock Splits"]]
            df = df.dropna()
            for col in df.columns:
                if df[col].dtype == 'object':
                    df[col] = df[col].astype(str).str.replace(r'[^\d.-]', '', regex=True)
            df = df.astype(float)
            df["Symbol"] = symbol
            standardized.append(df)
    return standardized

# Standardize the data from both DataFrames, then concatenate.
market_data = pd.concat(
    standardize_data(stock_data) + standardize_data(index_data)
).reset_index()

# Quick sanity check of resulted DataFrame
print(len(market_data))
print(market_data.head())
print(market_data.tail())

310037
                       Date       Open       High        Low      Close  \
0 2013-01-02 00:00:00-05:00  34.919998  35.400002  34.099998  35.119999
1 2013-01-03 00:00:00-05:00  35.000000  35.000000  34.160000  34.830002
2 2013-01-04 00:00:00-05:00  34.619999  34.889999  34.250000  34.389999
3 2013-01-07 00:00:00-05:00  34.150002  35.450001  34.150002  34.459999
4 2013-01-08 00:00:00-05:00  34.290001  34.639999  33.360001  33.709999

   Adj Close      Volume  Dividends  Stock Splits Symbol
0  20.561075  13767900.0        0.0           0.0   ABBV
1  20.391291  16739300.0        0.0           0.0   ABBV
2  20.133686  21372100.0        0.0           0.0   ABBV
3  20.174667  17897100.0        0.0           0.0   ABBV
4  19.735580  17863300.0        0.0           0.0   ABBV
                            Date         Open         High          Low  \
310032 2026-06-09 00:00:00-04:00  1901.479980  1924.859985  1862.640015
310033 2026-06-10 00:00:00-04:00  1884.530029  1885.489990  1846.349976
310034 2026-06-11 00:00:00-04:00  1855.459961  1894.469971  1844.699951
310035 2026-06-12 00:00:00-04:00  1900.359985  1900.359985  1862.520020
310036 2026-06-18 00:00:00-04:00  1892.689941  1908.670044  1872.400024

              Close    Adj Close       Volume  Dividends  Stock Splits  \
310032  1890.310059  1890.310059  376903800.0        0.0           0.0
310033  1848.209961  1848.209961  333802100.0        0.0           0.0
310034  1892.380005  1892.380005  354230200.0        0.0           0.0
310035  1892.589966  1892.589966  356900200.0        0.0           0.0
310036  1908.390015  1908.390015  194725508.0        0.0           0.0

           Symbol
310032  ^SP500-25
310033  ^SP500-25
310034  ^SP500-25
310035  ^SP500-25
310036  ^SP500-25

In [28]:
# Normalize the values in the Date column to ensure compatibility with future
# pandas operations for time series.
market_data['Date'] = pd.to_datetime(market_data['Date']).dt.normalize()
market_data.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,Symbol
0,2013-01-02 00:00:00-05:00,34.919998,35.400002,34.099998,35.119999,20.561075,13767900.0,0.0,0.0,ABBV
1,2013-01-03 00:00:00-05:00,35.000000,35.000000,34.160000,34.830002,20.391291,16739300.0,0.0,0.0,ABBV
2,2013-01-04 00:00:00-05:00,34.619999,34.889999,34.250000,34.389999,20.133686,21372100.0,0.0,0.0,ABBV
3,2013-01-07 00:00:00-05:00,34.150002,35.450001,34.150002,34.459999,20.174667,17897100.0,0.0,0.0,ABBV
4,2013-01-08 00:00:00-05:00,34.290001,34.639999,33.360001,33.709999,19.735580,17863300.0,0.0,0.0,ABBV

In [29]:
# Check for NaN, None, or NaT values
ohlcv = ["Open", "High", "Low", "Close", "Adj Close", "Volume"]
nan_data = market_data[market_data[ohlcv].isna().any(axis=1)]
print(len(nan_data))
print(nan_data.head())
print(nan_data.tail())

0
Empty DataFrame
Columns: [Date, Open, High, Low, Close, Adj Close, Volume, Dividends, Stock Splits, Symbol]
Index: []
Empty DataFrame
Columns: [Date, Open, High, Low, Close, Adj Close, Volume, Dividends, Stock Splits, Symbol]
Index: []

In [30]:
# Check zero (0) values for Open, High, Low, Close and Adj Close for the indices.
# Zero volume is immaterial since I only need price data for the
# indices for my analysis.
ohlc = ["Open", "High", "Low", "Close", "Adj Close"]
data_indices = market_data[market_data['Symbol'].str.startswith('^')]
zero_data_indices = data_indices[(data_indices[ohlc] == 0).any(axis=1)]
print(len(zero_data_indices))

0

In [31]:
# Check zero (0) values for Open, High, Low, Close, Adj Close, and Volume for stocks
# and NOBL.  Volume is important here since I will incorporate volume data
# during my analysis.
ohlcv = ["Open", "High", "Low", "Close", "Adj Close", "Volume"]
data_stocks= market_data[~market_data['Symbol'].str.startswith('^')]
zero_data_stocks = data_stocks[(data_stocks[ohlcv] == 0).any(axis=1)]
print(len(zero_data_stocks))

1225

In [32]:
# Let's break this number down by ticker symbols
print(zero_data_stocks['Symbol'].value_counts())

Symbol
AMCR    1223
CHD        1
ERIE       1
Name: count, dtype: int64

In [33]:
# Since there are only singleton recoreds for CHD and ERIE, let's look at these first
zero_data_stocks[zero_data_stocks['Symbol'].isin(['CHD', 'ERIE'])]

,Date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,Symbol
62514,2019-12-31 00:00:00-05:00,70.349998,70.349998,70.349998,70.349998,65.112663,0.0,0.0,0.0,CHD
98239,2013-12-13 00:00:00-05:00,70.279999,70.279999,70.279999,70.279999,51.991570,0.0,0.0,0.0,ERIE

For CHD there was zero volume for 12/31/2019, but the company was first added to the index in 2022.  For ERIE there was zero volume for 12/13/2013, but ERIE was added in 2025.  In light of this, these records can be deleted from the DataFrame.

In [34]:
# Now let's check the details for AMCR
zero_data_amcr = zero_data_stocks[zero_data_stocks['Symbol'] == 'AMCR']
print(zero_data_amcr.head())
print(zero_data_amcr.tail())

                           Date       Open       High        Low      Close  \
20316 2013-01-02 00:00:00-05:00  41.849998  41.849998  41.849998  41.849998
20317 2013-01-03 00:00:00-05:00  41.849998  41.849998  41.849998  41.849998
20318 2013-01-04 00:00:00-05:00  41.849998  41.849998  41.849998  41.849998
20320 2013-01-08 00:00:00-05:00  43.299999  43.299999  43.299999  43.299999
20321 2013-01-09 00:00:00-05:00  43.299999  43.299999  43.299999  43.299999

       Adj Close  Volume  Dividends  Stock Splits Symbol
20316  24.865166     0.0        0.0           0.0   AMCR
20317  24.865166     0.0        0.0           0.0   AMCR
20318  24.865166     0.0        0.0           0.0   AMCR
20320  25.726679     0.0        0.0           0.0   AMCR
20321  25.726679     0.0        0.0           0.0   AMCR
                           Date   Open   High    Low  Close  Adj Close  \
21931 2019-06-04 00:00:00-04:00  55.75  55.75  55.75  55.75   41.19981
21932 2019-06-05 00:00:00-04:00  55.75  55.75  55.75  55.75   41.19981
21933 2019-06-06 00:00:00-04:00  55.75  55.75  55.75  55.75   41.19981
21934 2019-06-07 00:00:00-04:00  55.75  55.75  55.75  55.75   41.19981
21935 2019-06-10 00:00:00-04:00  55.75  55.75  55.75  55.75   41.19981

       Volume  Dividends  Stock Splits Symbol
21931     0.0        0.0           0.0   AMCR
21932     0.0        0.0           0.0   AMCR
21933     0.0        0.0           0.0   AMCR
21934     0.0        0.0           0.0   AMCR
21935     0.0        0.0           0.0   AMCR

The very last record is in 2019.  AMCR was not added to the index until 2020, so it will be OK to delete these records.

In [35]:
# Drop zero (0) records for AMCR, CHD, and ERIE
market_data.drop(zero_data_stocks.index, inplace=True)
market_data.reset_index(drop=True, inplace=True) 
print(len(market_data))

308812

In [36]:
# Check for the existence of duped records
duplicate_count = market_data.duplicated(subset=['Date', 'Symbol']).sum()
print(duplicate_count)

0

In [37]:
# Save 3 DataFrames to respective .csv files
market_data.to_csv('market_data_for_time_series.csv', index=False)
aristocrats_complete.to_csv('aristocrats_complete_for_time_series.csv', index=False)
indices.to_csv('indices_for_time_series.csv', index=False)

In [38]:
stock_splits = market_data[market_data['Stock Splits'] > 0.0]\
                .sort_values(by='Date', ascending=True)
print(len(stock_splits))
print(stock_splits.tail())

# stock_splits.sort_values(by='Date', ascending=True)

37
                            Date        Open        High         Low  \
79402  2024-09-12 00:00:00-04:00  205.500000  207.490005  201.919998
113434 2025-05-22 00:00:00-04:00   40.860001   41.119999   40.139999
22372  2026-01-15 00:00:00-05:00   44.560001   45.490002   43.380001
35933  2026-02-10 00:00:00-05:00  165.979996  172.580002  164.410004
268218 2026-05-28 00:00:00-04:00   53.980000   54.139999   53.660000

             Close   Adj Close     Volume  Dividends  Stock Splits Symbol
79402   206.020004  202.960648  1340400.0        0.0         4.000   CTAS
113434   40.720001   39.884617  4420400.0        0.0         2.000   FAST
22372    44.160000   42.873783  4352500.0        0.0         0.200   AMCR
35933   171.679993  169.396317  4604400.0        0.0         1.272    BDX
268218   53.990002   53.990002   851600.0        0.0         2.000   NOBL

In [39]:
# stock_splits.groupby('Symbol').count()
stock_splits[stock_splits['Symbol']=='FAST'][['Date','Stock Splits']]

                            Date  Stock Splits
111926 2019-05-23 00:00:00-04:00           2.0
113434 2025-05-22 00:00:00-04:00           2.0